  on:
    workflow_dispatch:
    pull_request:
      paths:
        - "**/*.toml"
        - "**/*.lock"
        - "**.rs"
        - "**.wit"

  jobs:
    ci:
      uses: wasco-dev/workflows/.github/workflows/ci.yml@main
